name: Validate DAX
on: [push]
jobs:
  validate:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - name: Check DAX files
        run: |
          echo "Liste des fichiers DAX :"
          find . -name "*.dax" -exec echo {} \;
